// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v3.21.6
// source: app/testing-service/internal/conf/config.conf.proto

package conf

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ServiceConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TestingService *ServiceConfig_TestingService `protobuf:"bytes,1,opt,name=testing_service,json=testingService,proto3" json:"testing_service,omitempty"`
}

func (x *ServiceConfig) Reset() {
	*x = ServiceConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_testing_service_internal_conf_config_conf_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServiceConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceConfig) ProtoMessage() {}

func (x *ServiceConfig) ProtoReflect() protoreflect.Message {
	mi := &file_app_testing_service_internal_conf_config_conf_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceConfig.ProtoReflect.Descriptor instead.
func (*ServiceConfig) Descriptor() ([]byte, []int) {
	return file_app_testing_service_internal_conf_config_conf_proto_rawDescGZIP(), []int{0}
}

func (x *ServiceConfig) GetTestingService() *ServiceConfig_TestingService {
	if x != nil {
		return x.TestingService
	}
	return nil
}

type ServiceConfig_TestingService struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *ServiceConfig_TestingService) Reset() {
	*x = ServiceConfig_TestingService{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_testing_service_internal_conf_config_conf_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServiceConfig_TestingService) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceConfig_TestingService) ProtoMessage() {}

func (x *ServiceConfig_TestingService) ProtoReflect() protoreflect.Message {
	mi := &file_app_testing_service_internal_conf_config_conf_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceConfig_TestingService.ProtoReflect.Descriptor instead.
func (*ServiceConfig_TestingService) Descriptor() ([]byte, []int) {
	return file_app_testing_service_internal_conf_config_conf_proto_rawDescGZIP(), []int{0, 0}
}

func (x *ServiceConfig_TestingService) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

var File_app_testing_service_internal_conf_config_conf_proto protoreflect.FileDescriptor

var file_app_testing_service_internal_conf_config_conf_proto_rawDesc = []byte{
	0x0a, 0x33, 0x61, 0x70, 0x70, 0x2f, 0x74, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x2d, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x63,
	0x6f, 0x6e, 0x66, 0x2f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x15, 0x73, 0x61, 0x61, 0x73, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x74, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x1a, 0x17, 0x76, 0x61,
	0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x2f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x9b, 0x01, 0x0a, 0x0d, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x5c, 0x0a, 0x0f, 0x74, 0x65, 0x73, 0x74, 0x69,
	0x6e, 0x67, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x33, 0x2e, 0x73, 0x61, 0x61, 0x73, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x74, 0x65, 0x73, 0x74,
	0x69, 0x6e, 0x67, 0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x54, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x0e, 0x74, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x1a, 0x2c, 0x0a, 0x0e, 0x54, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x67,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x1a, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x42, 0x08, 0xfa, 0x42, 0x05, 0x72, 0x03, 0xd0, 0x01, 0x01, 0x52, 0x03,
	0x6b, 0x65, 0x79, 0x42, 0x7d, 0x0a, 0x15, 0x73, 0x61, 0x61, 0x73, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x74, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x42, 0x12, 0x53, 0x61,
	0x61, 0x73, 0x41, 0x70, 0x69, 0x54, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x43, 0x6f, 0x6e, 0x66,
	0x50, 0x01, 0x5a, 0x4e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x67,
	0x6f, 0x2d, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x2d, 0x73, 0x61, 0x61, 0x73, 0x2f, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2d, 0x6c, 0x61, 0x79, 0x6f, 0x75, 0x74, 0x2f, 0x61, 0x70, 0x70, 0x2f,
	0x74, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f,
	0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x63, 0x6f, 0x6e, 0x66, 0x3b, 0x63, 0x6f,
	0x6e, 0x66, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_app_testing_service_internal_conf_config_conf_proto_rawDescOnce sync.Once
	file_app_testing_service_internal_conf_config_conf_proto_rawDescData = file_app_testing_service_internal_conf_config_conf_proto_rawDesc
)

func file_app_testing_service_internal_conf_config_conf_proto_rawDescGZIP() []byte {
	file_app_testing_service_internal_conf_config_conf_proto_rawDescOnce.Do(func() {
		file_app_testing_service_internal_conf_config_conf_proto_rawDescData = protoimpl.X.CompressGZIP(file_app_testing_service_internal_conf_config_conf_proto_rawDescData)
	})
	return file_app_testing_service_internal_conf_config_conf_proto_rawDescData
}

var file_app_testing_service_internal_conf_config_conf_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_app_testing_service_internal_conf_config_conf_proto_goTypes = []interface{}{
	(*ServiceConfig)(nil),                // 0: saas.api.testing.conf.ServiceConfig
	(*ServiceConfig_TestingService)(nil), // 1: saas.api.testing.conf.ServiceConfig.TestingService
}
var file_app_testing_service_internal_conf_config_conf_proto_depIdxs = []int32{
	1, // 0: saas.api.testing.conf.ServiceConfig.testing_service:type_name -> saas.api.testing.conf.ServiceConfig.TestingService
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_app_testing_service_internal_conf_config_conf_proto_init() }
func file_app_testing_service_internal_conf_config_conf_proto_init() {
	if File_app_testing_service_internal_conf_config_conf_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_app_testing_service_internal_conf_config_conf_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServiceConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_testing_service_internal_conf_config_conf_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServiceConfig_TestingService); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_app_testing_service_internal_conf_config_conf_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_app_testing_service_internal_conf_config_conf_proto_goTypes,
		DependencyIndexes: file_app_testing_service_internal_conf_config_conf_proto_depIdxs,
		MessageInfos:      file_app_testing_service_internal_conf_config_conf_proto_msgTypes,
	}.Build()
	File_app_testing_service_internal_conf_config_conf_proto = out.File
	file_app_testing_service_internal_conf_config_conf_proto_rawDesc = nil
	file_app_testing_service_internal_conf_config_conf_proto_goTypes = nil
	file_app_testing_service_internal_conf_config_conf_proto_depIdxs = nil
}
